version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.cleanBuild
    container_name: frontend_prod
    ports:
      - '3000:3000'
    volumes:
      - ./:/frontend
      - /frontend/node_modules