version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.devBuild
    command: npm run start
    container_name: frontend_dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/frontend
      - /frontend/node_modules